apiVersion: v1
kind: Service
metadata:
  name: netflow-source-connector-service
  namespace: ti-sph
spec:
  ports:
    - port: 7000
      targetPort: 7000
  selector:
    app: netflow-source-connector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflow-source-connector
  namespace: ti-sph
spec:
  selector:
    matchLabels:
      app: netflow-source-connector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netflow-source-connector
    spec:
      containers:
        - name: netflow-source-connector
          image: 10.101.10.244:5000/netflow-source-connector:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
              hostPort: 7000
              protocol: TCP
          env:
            - name: KAFKA_IP
              value: "10.101.41.255"
            - name: KAFKA_PORT
              value: "9092"
            - name: NAME
              value: netflow-source-connector-service.ti-sph
            - name: API_PORT
              value: "7000"
            - name: REGISTRY_IP
              value: registry-service.ti-sph
            - name: REGISTRY_PORT
              value: "5000"
            - name: UPDATE_INTERVAL
              value: "60"
            - name: BENCHMARK_MODE
              value: "true"
