apiVersion: v1
kind: Service
metadata:
  name: odfe-kibana-service
  namespace: ti-sph
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: odfe-kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odfe-kibana
  namespace: ti-sph
  labels:
    app: odfe-kibana
spec:
  replicas:
  selector:
    matchLabels:
      app: odfe-kibana
  template:
    metadata:
      labels:
        app: odfe-kibana
    spec:
      nodeSelector:
        alias: worker1
      containers:
        - name: odfe-kibana
          image: opensearchproject/opensearch-dashboards:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
              hostPort: 5601
              protocol: TCP
          env:
            - name: OPENSEARCH_URL
              value: https://odfe-service:9200
            - name: OPENSEARCH_HOSTS
              value: https://odfe-service:9200
