apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: ti-dcp
spec:
  ports:
    - port: 5044
      targetPort: 5044
  selector:
    app: logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: ti-dcp
  labels:
    app: logstash
spec:
  replicas:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      nodeSelector:
        alias: worker1
      containers:
        - name: logstash
          image: logstash:7.12.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5044
              hostPort: 5044
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /usr/share/logstash/config/
          - name: pipeline
            mountPath: /usr/share/logstash/pipeline/
          - name: template
            mountPath: /usr/share/logstash/templates/
      volumes:
        - name: config
          hostPath:
            path: /media/palantir-nfs/SPH/volumes/logstash/config/
        - name: pipeline
          hostPath:
            path: /media/palantir-nfs/SPH/volumes/logstash/pipeline/
        - name: template
          hostPath:
            path: /media/palantir-nfs/SPH/volumes/logstash/templates/
